name = "Simulator"
uuid = "9831efa8-0d80-43cc-9004-a3150fbf83f2"
version = "1.0.0-DEV"
authors = ["PeterSomkuti <peter.somkuti@gmail.com>"]

[deps]
RetrievalToolbox = "46b81e12-0ded-426f-b207-2eae42eca022"

[compat]
RetrievalToolbox = "0.3.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
